### ISSUE TITLE
Auto versioning pipeline fails from fork

### ISSUE THREAD

**Issue by fmilthaler** [fmilthaler/FinQuant#124]
Failed pipeline: https://github.com/fmilthaler/FinQuant/actions/runs/5730526086/job/15530536877?pr=120

```
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
```
the above causes the failure. the below works on forks:
```
      - name: Checkout code
        uses: actions/checkout@v3
```
